spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/maxdb

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect 
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp